### ISSUE TITLE
Error on argis 10.5.1 when 

### ISSUE THREAD

**Issue by pazdror** [NCAR/wrf_hydro_arcgis_preprocessor#5]
Attached run settings and log
![run_settings](https://user-images.githubusercontent.com/24871303/37336007-bfd42870-26b8-11e8-8b36-f2e16
[20180310-1.zip.log](https://github.com/NCAR/wrf_hydro_arcgis_preprocessor/files/1806461/20180310-1.zip.log)
130bcb2.png)

**Comment by kmsampson** [comment]
The version of the tools you were using were not compatible with ArcGIS 10.5.1 (see the documentation on ArcGIS version compatability). However, if you use the latest release (v5.0), this should work in ArcGIS 10.5.1 as long as Spatial Analyst is enabled. Due to a workaround of an Esri bug, you will not get identical results using 10.5.1 as you would using 10.3.1 or 10.6, but it will be very close.
